### ISSUE TITLE
UI: 侧边城市导航栏

### ISSUE THREAD

**Issue by yjl9903** [yjl9903/resonance-market#12]
https://blog.onekuma.cn/mdio

<img width="1121" alt="image" src="https://github.com/yjl9903/resonance-market/assets/30072175/6ee9683a-dcf1-4174-88cf-5386da8a2052">

**Comment by yjl9903** [comment]
不知道各种屏幕大小宽度够不够？

移动端如何处理？

**Comment by Ximu-Luya** [comment]
@yjl9903 已用城市筛选器解决此问题，不过UI样式应该还可以优化

![image](https://github.com/yjl9903/resonance-market/assets/53012237/56671e3b-bf24-4f74-817e-a6b1577ac5ec)
