### ISSUE TITLE
录入功能优化建议

### ISSUE THREAD

**Issue by MoliereZhu** [yjl9903/resonance-market#14]
1、建议出个可以把所在城市买卖价格批量录入的功能，选定城市，下拉选择商品进行录入，横向排列，每列录入一种商品。
2、价位建议增加手动输入数值的选项，另外价格和价位理论上应存在联动关系，只录入一个能自动得出另一个，基础数据可以参考老黑的雷索纳斯手册表格。

**Comment by yjl9903** [comment]
对于第2点已经已经实现了，现在你只要：

1. 选一个城市，会自动导入最新的记录
2. 修改价格，价位也会更着变化
3. 修改趋势

第1点在计划中

**Comment by MoliereZhu** [comment]
> 对于第2点已经已经实现了，现在你只要：
> 
> 1. 选一个城市，会自动导入最新的记录
> 2. 修改价格，价位也会更着变化
> 3. 修改趋势
> 
> 第1点在计划中

感谢大佬的更新，新的批量录入指定城市卖出价格功能刚试了下，一次想录十几种商品时打字搜索商品多少有点麻烦且低效，建议加个首字母筛选之类的，如果能做出wiki常用的上面一栏点筛选标签，下面一栏显示带图片的筛选结果的那种版面就最好了。

**Comment by Ximu-Luya** [comment]
我确实有在考虑将商品名称重构为图片+商品名称，这样我感觉会更直观一点。 @yjl9903 不过现在咱们没有解包的图片数据对吧

**Comment by Megumism** [comment]
如果能够实现截图识别自动录入，可能数据更新会更及时一点，手动输入还是有点难。

总之star了。

**Comment by Ximu-Luya** [comment]
目前已支持自动化数据上报，人工上报功能优先级降低，暂时不再考虑此优化
