### ISSUE TITLE
[功能建议] 加入ResoData跑商数据接口实现自动化更新

### ISSUE THREAD

**Issue by kmou424** [yjl9903/resonance-market#18]
介绍一下自己写的 API 接口：https://github.com/kmou424/resonance-resodata

希望开发者了解一下这个项目，召集大🔥一起参与到完善工作中。目前还有很多东西需要完善，但实现数据更新就只需要补全项目中的映射表文件（在项目中有介绍）。如果有更多改进或功能方面的建议可以加入QQ群，我已经写在项目README中了。
相关后端代码不便开源，dddd

UPDATE：参与完善工作可以直接来填写在线表格，我会定期收集整理提交到GitHub：[腾讯文档-商品-站点-ID映射表](https://docs.qq.com/sheet/DSnJpUE5MQUxVZWFD?tab=jyci4r)(https://docs.qq.com/sheet/DSnJpUE5MQUxVZWFD?tab=jyci4r)

**Comment by yjl9903** [comment]
意思是你自动抓了游戏数据吗？（

**Comment by yjl9903** [comment]
@Ximu-Luya 新页面可以考虑用一用？

但是目前网站访问量还是比较大的，每小时都有3k~6k的PV，可能要我们要做缓存

**Comment by Ximu-Luya** [comment]
@yjl9903 目前我暂时以本项目的数据进行开发的，不过本来计划就需要这种类似的功能，感谢大佬 @kmou424  提供，我会研究看看

**Comment by kmou424** [comment]
> 意思是你自动抓了游戏数据吗？（

是这个意思

**Comment by yjl9903** [comment]
> @Ximu-Luya 新页面可以考虑用一用？
> 
> 但是目前网站访问量还是比较大的，每小时都有3k~6k的PV，可能要我们要做缓存

刚说完数据库就被打爆了

**Comment by Ximu-Luya** [comment]
@yjl9903 现在代码里是隔10秒就自动刷新，感觉可以去掉自动刷新或者增大循环时间。
1. 去掉自动新增一个手动刷新按钮
2. 增大自动刷新时间为1分钟/5分钟/10分钟

**Comment by yjl9903** [comment]
> @yjl9903 现在代码里是隔10秒就自动刷新，感觉可以去掉自动刷新或者增大循环时间。
> 
> 1. 去掉自动新增一个手动刷新按钮
> 2. 增大自动刷新时间为1分钟/5分钟/10分钟

这不解决问题，口胡了某种类似 cow、stale-while-revalidate 的分布式缓存机制：https://github.com/yjl9903/memofunc?tab=readme-ov-file#memoexternal

**Comment by Ximu-Luya** [comment]
大佬太强了，我只是服务端苦手，原来只做过node和python的单点服务，后端服务相关的只得等后续再学习学习了。
