### ISSUE TITLE
脚本抓包能直接抓到所有数据

### ISSUE THREAD

**Issue by puresox** [yjl9903/resonance-market#2]
### Clear and concise description of the problem

如题，脚本抓包模拟器，能抓到当前城市所有物品买卖数据，不需要别人上传

**Comment by FeirBlox** [comment]
请求包参数中sig、rty需要解决，不然时间戳不对。sig应该是什么值的md5。rty不是单纯的时间戳，python中达不到那样的精度。

**Comment by puresox** [comment]
不知道怎么加密的，只能通过中间人拦截代理进行抓包

**Comment by Raaaaaaat** [comment]
> 请求包参数中sig、rty需要解决，不然时间戳不对。sig应该是什么值的md5。rty不是单纯的时间戳，python中达不到那样的精度。

我最近也在试，sig目前没办法解决，rty我感觉是毫秒级别的时间戳，用go试了以下，数据看起来对的上

**Comment by puresox** [comment]
> > 请求包参数中sig、rty需要解决，不然时间戳不对。sig应该是什么值的md5。rty不是单纯的时间戳，python中达不到那样的精度。
> 
> 我最近也在试，sig目前没办法解决，rty我感觉是毫秒级别的时间戳，用go试了以下，数据看起来对的上

看我写的抓包脚本https://github.com/puresox/resonance-capture

**Comment by yjl9903** [comment]
@puresox 好的呀

希望你能直接用脚本上传数据到平台里 :)

接口信息（可以自己 F12 看看）：

POST https://resonance.breadio.wiki/api/log

请求 JSON body：

```ts
const schema = z.object({
  name: z.string(),
  sourceCity: z.string(),
  targetCity: z.string(),
  type: z.enum(['buy', 'sell']),
  trend: z.enum(['up', 'same', 'down']),
  price: z.number().gt(0),
  percent: z.number().gt(0).lt(200),
  uploadedAt: z.coerce.date()
});
```

**Comment by puresox** [comment]
@yjl9903 一次只能post一条数据吗，游戏里有100多件商品，每个商品都能从一个地方卖往另外8个地方，总共会需要post几千条呢，我觉得应该设计一种高效的数据结构，一次性上报所有的数据

**Comment by yjl9903** [comment]
给你加一个

**Comment by kmou424** [comment]
自动化获取数据我这里已经实现了，只是sig、arg、rty算法不方便开源，不过可以来帮忙完善id和商品的对应关系，我在README里有写。
link：https://github.com/kmou424/resonance-resodata

**Comment by Ximu-Luya** [comment]
已接入索思学会提供的数据，实现数据自动化，故关闭此issue
