### ISSUE TITLE
夜色模式下，部分Icon字体颜色错误导致不可见

### ISSUE THREAD

**Issue by Ximu-Luya** [yjl9903/resonance-market#20]
### Describe the bug

如下图
<img width="345" alt="image" src="https://github.com/yjl9903/resonance-market/assets/53012237/01d66093-51db-453d-8cf5-6a3974d6626b">

### Reproduction

使用夜色模式访问页面

### System Info

```Shell
Chrome, Mac, 夜色模式
```

### Used Package Manager

None

**Comment by yjl9903** [comment]
我发烧了，你看着修一修吧（

**Comment by Ximu-Luya** [comment]
@yjl9903 保重好身体，我页面里也用到了你这个组件，我一块弄弄

**Comment by yjl9903** [comment]
`text-base-100` ~ `text-base-900` 应该都用这个字体颜色就行了

**Comment by Ximu-Luya** [comment]
OK，看过代码了

**Comment by Velsun3366** [comment]
> OK，看过代码了

建议的话最终就整一个可切换的switch，注入两套CSS就行了

**Comment by Ximu-Luya** [comment]
改outline那个系列了，那个才支持。下面的时间图标就是outline系列的

**Comment by yjl9903** [comment]
不支持吗，改 bg-[xxx] 也不行吗

**Comment by Ximu-Luya** [comment]
![image](https://github.com/yjl9903/resonance-market/assets/53012237/20c083e0-4c0c-4124-b548-a3070cbd7716)

@yjl9903  bg-[xxx]肯定是不行的，你可以看看效果就明白了。icon都是响应文字颜色
