### ISSUE TITLE
支持货物出售按不同城市利润高低倒排序

### ISSUE THREAD

**Issue by Ximu-Luya** [yjl9903/resonance-market#25]
### Clear and concise description of the problem

在做新页面的时候，我放弃了原本我那一套表格渲染，因为之前我是直接扒的接口，和当前项目中实际存储的数据大相径庭。于是我开始基于现有的表格渲染做优化。

目前页面中并未对各城市的利润之间进行对比，仅提供了单位利润展示，我稍微改变了一下表格结构，使其支持按利润高低对货物的售出城市进行从高到低的排序。

### Suggested solution

在首页中表格，每一行货物的可出售城市，将按利润从高到低排序

如果你觉得可以的话，我可以提一个PR修改当前页面中的展示。

当然，我认为可能更好的方式是可能是保留两者，让用户可以自行切换。

### Additional context

实际效果如下：

![image](https://github.com/yjl9903/resonance-market/assets/53012237/5a7fc455-78cf-448f-8ccc-aba54624542d)

**Comment by yjl9903** [comment]
好的呀

**Comment by yjl9903** [comment]
设置我想的有两种：

- 导航栏里加一个开关
- 城市标题的最右边加一个 DropdownMenu

**Comment by Ximu-Luya** [comment]
> 设置我想的有两种：
> 
> * 导航栏里加一个开关
> * 城市标题的最右边加一个 DropdownMenu

这个我建议是不在导航栏也不在每个城市标题旁加开关。

1. 要看这种收益，一般应该是整个列表都要看最高收益，在城市标题旁，就得一个一个城市挨着点。
2. 放在导航栏，其他页面就也能看到这个开关了。

我个人理解是放在第一个城市标题上方和导航栏的下方，我可以把我那部分东西扒拉出来到主页面提个PR，到时候看看效果。

**Comment by yjl9903** [comment]
> > 设置我想的有两种：
> 
> > 
> 
> > * 导航栏里加一个开关
> 
> > * 城市标题的最右边加一个 DropdownMenu
> 
> 
> 
> 这个我建议是不在导航栏也不在每个城市标题旁加开关。
> 
> 
> 
> 1. 要看这种收益，一般应该是整个列表都要看最高收益，在城市标题旁，就得一个一个城市挨着点。
> 
> 2. 放在导航栏，其他页面就也能看到这个开关了。
> 
> 
> 
> 我个人理解是放在第一个城市标题上方和导航栏的下方，我可以把我那部分东西扒拉出来到主页面提个PR，到时候看看效果。

感觉这个位置不好看

导航栏里添加设置，设置里有个开关呢

目前有一个MenubarRadioGroup组件可以直接实现吧

**Comment by Ximu-Luya** [comment]
明白你的意思了，也是一个悬浮下拉菜单，感觉可以

**Comment by Velsun3366** [comment]
> 可以帮忙把这边重构一下吗：
> 
> https://github.com/yjl9903/resonance-market/blob/50cf3d61d2c0e0e1b7f9a7588c47c0d551cb06ad/stores/latest.ts#L3-L35
> 
> 希望抓完数据，把实时数据添加到 ProductInfo 在一起，组件里所有就用合并后的数据

这段我来试试吧，我把这个pinia写标准点

**Comment by Ximu-Luya** [comment]
@yjl9903 OK
