### ISSUE TITLE
关于添加到目标城市的总收益栏

### ISSUE THREAD

**Issue by 2834467732** [yjl9903/resonance-market#26]
我感觉可以在每个本地城市最下面一行添加一个总收益数，可以显示到另一个城市所有材料正值利润的总和，这样的话就不用一个个加起来对比了，如果很麻烦的话当我没说。
总之谢谢你写的网站。

**Comment by yjl9903** [comment]
有点没明白

**Comment by 2834467732** [comment]
笨小孩
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yjl9903/resonance-market"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月8日(星期五) 中午12:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yjl9903/resonance-market] 关于添加到目标城市的总收益栏 (Issue #26)





 
有点没明白
