### ISSUE TITLE
关于自动获取货价

### ISSUE THREAD

**Issue by LeoSunw** [yjl9903/resonance-market#33]
大佬我有8个废了的号可以免费提供作为获取实时价格用途，但是就需要大佬写个爬数据的脚本，看有需要吗？正好一个点驻扎一个账号，就是不知道价格更新不出站会不会更新，

**Comment by Ximu-Luya** [comment]
现在已经有自动获取货价的数据项目了，不过咱们暂时还没有接入，需要等另一个大佬 @yjl9903 看看服务端代码如何设计一下

**Comment by yjl9903** [comment]
See #2 

但好像没有有脚本朋友，用接口传数据

**Comment by Ximu-Luya** [comment]
之前联系咱们的那个resodata项目 #18  ，我看他们数据已经较为完善了，个人感觉可以从服务端定时同步他们的数据

**Comment by yjl9903** [comment]
唉，弄一下感觉好麻烦

**Comment by Ximu-Luya** [comment]
哈哈哈，咕咕咕了。要是你嫌实在麻烦，我后续也可以看一看服务端代码，看我能不能搞

**Comment by yjl9903** [comment]
@Ximu-Luya Nuxt 目前对 cron scheduled tasks 的支持还比较 undocumented

但是理论上都不需要写在服务端上，只要有人能：开一台电脑定时跑脚本，把那边的数据同步过来就行了

接口见 #2

**Comment by Ximu-Luya** [comment]
OK，那我感觉可以写一个小的python脚本放在我服务器上跑，我这两天研究一下。另外脚本上传数据就会有非常多记录了，你看处理一下我提到的这个问题呢？ #31

**Comment by Night-stars-1** [comment]
![image](https://github.com/yjl9903/resonance-market/assets/99261160/f396aa21-6bbe-4d7a-ae34-e5c02d9c8177)
我这边有一点进展了，不知道能不能弄出来

**Comment by Night-stars-1** [comment]
> ![image](https://private-user-images.githubusercontent.com/99261160/312507191-f396aa21-6bbe-4d7a-ae34-e5c02d9c8177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDIxOTgsIm5iZiI6MTcxMDM0MTg5OCwicGF0aCI6Ii85OTI2MTE2MC8zMTI1MDcxOTEtZjM5NmFhMjEtNmJiZS00ZDdhLWFlMzQtZTVjMDJkOWM4MTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE0NTgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzNzEyMjZhYmZmMzVmNDFjYjdjNDU2ODlkYTgxZjdjNmY0M2VjYjE3YTIzN2NjMjU3MDc0Y2IzYWI3MDg5NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1A-03AjACik3r2B0uvK_B5ZZXPzHdr6-NYM-KUG23DQ) 我这边有一点进展了，不知道能不能弄出来

找到应该是找到盐值了
![image](https://github.com/yjl9903/resonance-market/assets/99261160/00c139af-428d-4966-a72a-a629314f21f3)

**Comment by Night-stars-1** [comment]
出来了
![image](https://github.com/yjl9903/resonance-market/assets/99261160/d6a6e124-5310-4eb6-949c-74acd6a6934d)
![image](https://github.com/yjl9903/resonance-market/assets/99261160/d4ce5591-c1c4-4941-98ea-13535eeacdb8)

**Comment by Night-stars-1** [comment]
一整套都解决了，明天调整一下代码结果应该就可以上传了
