### ISSUE TITLE
建议：在边侧增加一个固定的导航栏可快速移动到对应的城市

### ISSUE THREAD

**Issue by susuIsHere1017** [yjl9903/resonance-market#35]
上下翻找还是有些麻烦了，能在页面增加一个固定的导航栏，给每个城市的框定一个锚点来方便快速查看详情吗？
谢谢

**Comment by Ximu-Luya** [comment]
@susuIsHere1017 数据表格页面添加了一个城市筛选器，应该能满足你的需求了

**Comment by susuIsHere1017** [comment]
太棒了，非常感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月20日(星期三) 凌晨2:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yjl9903/resonance-market] 建议：在边侧增加一个固定的导航栏可快速移动到对应的城市 (Issue #35)





 
@susuIsHere1017 数据表格页面添加了一个城市筛选器，应该能满足你的需求了
