### ISSUE TITLE
访问不到url

### ISSUE THREAD

**Issue by Livresse** [yjl9903/resonance-market#36]
### Describe the bug

家里和公司的电脑都无法访问网址
![7 9`08IZ(YLNLD_UV2D(2{O](https://github.com/yjl9903/resonance-market/assets/62112045/5215a333-f97d-4444-9ef0-09042a3ff850)
![68OWCF%G{BP3LVF}KU3 DB](https://github.com/yjl9903/resonance-market/assets/62112045/13b14539-fa46-4cda-a7b5-2a35fe3b77cb)

### Used Package Manager

None

**Comment by yjl9903** [comment]
目前一切正常

网站部署和访问由 cloudflare 提供，在国内部分区域可能连 cloudflare 有困难

你可能需要检查自己的网络连接状况
