### ISSUE TITLE
关于数据上传

### ISSUE THREAD

**Issue by Night-stars-1** [yjl9903/resonance-market#37]
### Clear and concise description of the problem

https://resonance.breadio.wiki/api/logs
这个链接还可以用吗

另外看介绍他的包体是这样的
```
  name: z.string(),
  sourceCity: z.string(),
  targetCity: z.string(),
  type: z.enum(['buy', 'sell']),
  trend: z.enum(['up', 'same', 'down']),
  price: z.number().gt(0),
  percent: z.number().gt(0).lt(200),
  uploadedAt: z.coerce.date()
```
其中targetCity和percent似乎是冗余信息，可以本地生成

**Comment by yjl9903** [comment]
targetCity 不是

type 和 percent 确实是冗余的，设计如此

**Comment by Night-stars-1** [comment]
> targetCity 不是
> 
> type 和 percent 确实是冗余的，设计如此

在城市里卖东西的时候价格只与商品有关，和城市无关，至少服务端返回的数据是这样的

**Comment by Night-stars-1** [comment]
另外我想定时往这边发生游戏里商品的数据，进行同步，
https://resonance.breadio.wiki/api/logs
这个链接还可以用吗我测试的时候返回的是html代码
如果请求成功返回的是什么样子的数据

**Comment by yjl9903** [comment]
正常的（插入成功了几条返回几）

![image](https://github.com/yjl9903/resonance-market/assets/30072175/0b9c2726-8aca-45d3-b609-5c48b61b417a)

![image](https://github.com/yjl9903/resonance-market/assets/30072175/287f1814-34d1-4ba5-a2a6-7153e2b452f9)

**Comment by yjl9903** [comment]
> > targetCity 不是
> > type 和 percent 确实是冗余的，设计如此
> 
> 在城市里卖东西的时候价格只与商品有关，和城市无关，至少服务端返回的数据是这样的

哪个城市，sourceCity + name 是商品从哪个城市买的什么商品，targetCity 是卖到什么城市（或在当前城市买入）

不管有关或者无关，就按照现在的样子冗余多条日志上报吧

毕竟一开始我也不能得知游戏里是什么机制

**Comment by Ximu-Luya** [comment]
@yjl9903 我这边测试数据量太大了，一次有272条数据，接口返回400了

**Comment by Night-stars-1** [comment]
> @yjl9903 我这边测试数据量太大了，一次有272条数据，接口返回400了

![image](https://github.com/yjl9903/resonance-market/assets/99261160/6b9fb4e0-96fc-450b-aed8-e08d5edbf7db)
我也是

**Comment by Ximu-Luya** [comment]
我分段上传了

**Comment by Night-stars-1** [comment]
> 我分段上传了

👌，你是都爬下来了吗，是的话我就不传了

**Comment by Ximu-Luya** [comment]
有现成的数据项目，你是自己爬的吗？

**Comment by Night-stars-1** [comment]
> 有现成的数据项目，你是自己爬的吗？

是的，我没有找到现成的，之前有一个但是加了鉴权我认为这会不可控，所以自己写了一个

**Comment by Ximu-Luya** [comment]
@Night-stars-1 鉴权有什么问题吗？这个我不太懂

**Comment by Night-stars-1** [comment]
> @Night-stars-1 鉴权有什么问题吗？这个我不太懂

没什么问题，我的意思是接口无法自由调用，如果出现更多限制到时候不好办，和有没有鉴权更新不大。
只是我觉得自己弄一个稳一些

**Comment by Ximu-Luya** [comment]
> > @Night-stars-1 鉴权有什么问题吗？这个我不太懂
> 
> 没什么问题，我的意思是接口无法自由调用，如果出现更多限制到时候不好办，和有没有鉴权更新不大。 只是我觉得自己弄一个稳一些

我了解的信息是，加鉴权只是为了防止数据被滥用或恶意大量访问，对此我认为还是能够理解的

**Comment by Ximu-Luya** [comment]
> > @yjl9903 我这边测试数据量太大了，一次有272条数据，接口返回400了
> 
> 现在每 10 条一次 sql insert （see L17），在试试
> 
> https://github.com/yjl9903/resonance-market/blob/3d84b563e7d066d61c3c9aec81693d4a2cb027cf/server/api/logs.post.ts#L10-L53

我切成20条本地试了没问题，不过线上的话，我按着你这个10条来切吧。

**Comment by yjl9903** [comment]
> 发现一个问题，咱们数据里的“斑节虾”字错了，写成了“班节虾”，同步数据的时候漏掉了（笑哭

先错着，改起来有点麻烦

**Comment by yjl9903** [comment]
> 猜到了，那我脚本兼容一下。看起来我可能还需要一个获取全货物信息与交易链路的接口，要不线上的基准数据更新了，我这边脚本上传的数据就是按旧的来算的了

数据库里的价格不太对，以这个文件为准吧 utils/products.json

**Comment by Ximu-Luya** [comment]
突然想到好像也可以在脚本中直接获取仓库里的这个JSON，那没问题了。

另外我这边发现，金箔和金线材，卖到铁盟哨站的数据缺失了。

**Comment by yjl9903** [comment]
因为我没有老黑表格的权限，不知道有没有朋友更新一下数据

**Comment by Ximu-Luya** [comment]
数据就咱们自己维护了吧？还需要老黑的表格权限吗

**Comment by Ximu-Luya** [comment]
@yjl9903 也是，那我去申请一下

**Comment by Ximu-Luya** [comment]
@yjl9903 另外奇怪的是，我脚本调本地接口没问题，调线上接口403了

**Comment by yjl9903** [comment]
> 发现一个问题，咱们数据里的“斑节虾”字错了，写成了“班节虾”，同步数据的时候漏掉了（笑哭

迁移到了 斑节虾

**Comment by Ximu-Luya** [comment]
这么快，好好好

**Comment by yjl9903** [comment]
> @yjl9903 另外奇怪的是，我脚本调本地接口没问题，调线上接口403了

是被 cloudflare 的防火墙挡了吗，还是服务端返回了什么东西

**Comment by Ximu-Luya** [comment]
> @yjl9903 另外奇怪的是，我脚本调本地接口没问题，调线上接口403了

感觉是背cf的墙挡了，服务端除了返回403，还返回了一段HTML代码，看了一下里面的信息，看起来像是cf的锅

**Comment by yjl9903** [comment]
> > @yjl9903 另外奇怪的是，我脚本调本地接口没问题，调线上接口403了
> 
> 感觉是背cf的墙挡了，服务端除了返回403，还返回了一段HTML代码，看了一下里面的信息，看起来像是cf的锅

可能不能发太快

给你开个口子看看，绕过了防火墙：User-Agent 写 resonance-market

**Comment by Ximu-Luya** [comment]
> > > @yjl9903 另外奇怪的是，我脚本调本地接口没问题，调线上接口403了
> > 
> > 
> > 感觉是背cf的墙挡了，服务端除了返回403，还返回了一段HTML代码，看了一下里面的信息，看起来像是cf的锅
> 
> 可能不能发太快
> 
> 给你开个口子看看，绕过了防火墙：User-Agent 写 resonance-market

OK，成功了，可以看看效果了。

**Comment by Ximu-Luya** [comment]
好耶，可以有实时数据了🎉

不过我再在本地调一下，还有一些细节问题。

铁盟哨站和修格里的这个弹丸加速装置真的很烦人耶，当时我自己做表格的时候处理你的接口数据的时候也弄了很久。它是唯一一个能在俩地方买到的物品。

**Comment by Ximu-Luya** [comment]
自动化数据上传TODO List：

- [ ] 解决“弹丸加速装置”的特殊兼容逻辑
- [ ] 上报前，自动获取仓库中最新商品数据
- [ ] 上线脚本

**Comment by Ximu-Luya** [comment]
@yjl9903 脚本已经在我云机器上跑起来了，每隔5分钟同步一次数据，可以关注一下。

**Comment by Ximu-Luya** [comment]
resolve #33

**Comment by yjl9903** [comment]
> @yjl9903 有一个小问题现在，我云服务器是国内的，索思他们提供的数据实在荷兰的，所以经常拉接口数据的时候失败，你有什么好一点的办法吗？

加一些重试？给服务器挂一下代理？

**Comment by Ximu-Luya** [comment]
> > @yjl9903 有一个小问题现在，我云服务器是国内的，索思他们提供的数据实在荷兰的，所以经常拉接口数据的时候失败，你有什么好一点的办法吗？
> 
> 加一些重试？给服务器挂一下代理？

感觉重试不解决问题，请求去拉数据的时候比较慢，就算重试也不稳定。

我有代理但是服务上之前我用的那个命令行clash，似乎在上次clash风波之后删库了，找不到了555

**Comment by Night-stars-1** [comment]
> > > @yjl9903 有一个小问题现在，我云服务器是国内的，索思他们提供的数据实在荷兰的，所以经常拉接口数据的时候失败，你有什么好一点的办法吗？
> > 
> > 
> > 加一些重试？给服务器挂一下代理？
> 
> 感觉重试不解决问题，请求去拉数据的时候比较慢，就算重试也不稳定。
> 
> 我有代理但是服务上之前我用的那个命令行clash，似乎在上次clash风波之后删库了，找不到了555

改名了
网站还有可以定位到的
https://github.com/juewuy/ShellClash

**Comment by yjl9903** [comment]
@Ximu-Luya 给你拿 cloudflare 做了个简单的请求转发，不知道会不会好一点

https://resonance.breadio.wiki/api/resodata/abc/def/ghi -> https://reso-data.kmou424.moe/abc/def/ghi

**Comment by Ximu-Luya** [comment]
> @Ximu-Luya 给你拿 cloudflare 做了个简单的请求转发，不知道会不会好一点
> 
> https://resonance.breadio.wiki/api/resodata/abc/def/ghi -> https://reso-data.kmou424.moe/abc/def/ghi

我试试看，能不能行

**Comment by Ximu-Luya** [comment]
@Night-stars-1 哇喔，非常感谢分享

**Comment by Ximu-Luya** [comment]
> @Ximu-Luya 给你拿 cloudflare 做了个简单的请求转发，不知道会不会好一点
> 
> https://resonance.breadio.wiki/api/resodata/abc/def/ghi -> https://reso-data.kmou424.moe/abc/def/ghi
> 
> https://github.com/yjl9903/resonance-market/blob/77a69b804af1896a0383a65ef7230d767203aa3d/server/api/resodata/%5B...slug%5D.ts#L1-L6

索思学会的API需要通过查询字符串参数传UUID鉴权，看起来这里把查询字符串参数忽略了，导致我这提示uuid失效，感觉转发是有效的

**Comment by Ximu-Luya** [comment]
另外再麻烦你再帮忙代理一下 `https://raw.githubusercontent.com/yjl9903/resonance-market/main/utils/products.json` 这个吧，用于更新商品数据之后上报时计算的是最新的值

**Comment by yjl9903** [comment]
@Ximu-Luya 修了，把 search params 也带上了

添加了两个接口：https://resonance.breadio.wiki/api/info/products 和 https://resonance.breadio.wiki/api/info/cities

**Comment by yjl9903** [comment]
问题不大
