### ISSUE TITLE
部分地区或部分特殊情况无法访问此项目

### ISSUE THREAD

**Issue by Ximu-Luya** [yjl9903/resonance-market#40]
一般多见于特殊地区或校园网，导致dns解析失败或其他缘故，无法访问咱们的 雷索纳斯市场。

我有国内备案了的域名，改一改前缀可以转发，这个能搞吗？

**Comment by yjl9903** [comment]
目前部署用的是 cloudflare + worker 订阅（5刀/月），每日有5百万个请求

![image](https://github.com/yjl9903/resonance-market/assets/30072175/b9db0bed-d20a-4539-abff-6ad721e2b0d0)

那考虑做个镜像站：使用国内的云服务器搞个 nginx 反代一下？

**Comment by Ximu-Luya** [comment]
@yjl9903 对，我是这么想的。我有一台国内的轻量云，也有备案号的域名，nginx配一下反代就可以。

不过看起来好像反代cf不是想象中配个proxy_pass就行的……

**Comment by yjl9903** [comment]
@Ximu-Luya 我也没做过这种操作，不太懂 😭

**Comment by Ximu-Luya** [comment]
@yjl9903 那我研究一下

**Comment by yjl9903** [comment]
@Ximu-Luya 或者前两天 cf 不是自家开源了一个 nginx 的替代品 https://github.com/cloudflare/pingora

不知道能不能用，才出没几天估计没啥教程

**Comment by Ximu-Luya** [comment]
你试试这个域名访问一下看看，我按照网上的配了一下，但页面提示是cf的block页，看是不是能够给个白名单？

http://resonance-market.ximustudio.top

**Comment by Ximu-Luya** [comment]
我突然在想，咱们访问量页不小，我这小水管服务器撑得住吗哈哈哈

**Comment by Ximu-Luya** [comment]
> > 你试试这个域名访问一下看看，我按照网上的配了一下，但页面提示是cf的block页，看是不是能够给个白名单？
> > http://resonance-market.ximustudio.top
> 
> 好像转到了你的博客了

啊，我以为你昨晚试了，我白天已经把转发规则下掉了。现在我又加上了你再试试

**Comment by Ximu-Luya** [comment]
我看有原本访问不了的人反馈现在可以正常访问了，不知道是你调了cf的什么配置吗hhh

另外用Nginx反代做镜像站成本现阶段来看有点高，网上的方法都试了，如果有另外可以直接用的方案，再reopen这个issue把，我先关了
