### ISSUE TITLE
建议: 显示单票金额 累加所有特产商品在其他地区贩卖单票总和

### ISSUE THREAD

**Issue by HZTT** [yjl9903/resonance-market#42]
建议直白显示单票金额，以及加个累加所有特产商品在其他地区贩卖单票总和

**Comment by Ximu-Luya** [comment]
第一点计划做，会像现在利润排序一样，左做成一个设置选项。

第二点也在计划做，不过时间可能会稍微长一点，毕竟是一整套计算规则，敬请期待哈~

不过非常欢迎你再提更细致的想法~
