### ISSUE TITLE
[UI] 深色模式下 checkbox 看不见

### ISSUE THREAD

**Issue by sjfhsjfh** [yjl9903/resonance-market#44]
### Describe the bug

rt
<img width="407" alt="图片" src="https://github.com/yjl9903/resonance-market/assets/58244206/46eadc9c-a303-4376-b4e0-46e1cc4d21e4">

### Reproduction

开启深色模式

### System Info

```Shell
macOS 14.4 (23E214)
Firefox 123.0.1 (64 位)
```

### Used Package Manager

None

**Comment by yjl9903** [comment]
@Ximu-Luya 我记得这个不是重构了吗？

**Comment by Ximu-Luya** [comment]
这个应该是批量买入卖出上报那里的表单，我重构了check，不过我确实也发现我忘记适配深色模式了，害

这个我优先修一下
