### ISSUE TITLE
[数据缺失] 部分交易基准数据缺失

### ISSUE THREAD

**Issue by Ximu-Luya** [yjl9903/resonance-market#47]
举例：金箔、纯金线材，这俩到铁盟哨站和战备工厂的基准数据都没有。

原因：全商品数据那个csv，数据过时了，导致处理出来的product.json数据缺失。

@yjl9903 解决todo list: 

- [x] 重新从数据源表中导出全商品统计csv（不再使用老黑表格中的csv）
- [x] 重新处理数据生成product.json（已用索思学会数据生成）
- [x] 回归测试，之前部分commit中直接修改了csv，重新导出数据之后是否会影响？（不再涉及csv数据）
- [x] 更新接口 `/api/info/products` 中的返回数据，以便自动更新数据脚本能够正常上报此次csv更新后的补充数据（接口数据直接来自于product.json）不影响

**Comment by yjl9903** [comment]
1. 要把老黑的表格导出：https://docs.qq.com/sheet/DQlZhS1RQcHNranRU?u=76e178d9d96644649dfd6f933bf0c16d&tab=000003 （UTF-8 编码 LF 的 csv 格式，覆盖仓库里的 csv 文件）
2. `tsx ./scripts/export-info.ts`
3. 不影响
4. 不影响

**Comment by Ximu-Luya** [comment]
@yjl9903 已经可以不需要老黑表格的数据了，索斯学会有所有商品的基准数据。

不过相比起来缺了两个字段：
1. product中的type，标识商品是哪种类型（特产、手工制作、普通），这个我问问索思学会有没有办法提供
2. transaction里的milage，我看这字段完全没有应用的，我脚本导出的时候就全手动置0了

**Comment by yjl9903** [comment]
有一些字段单纯就是冗余的/应对未来新需求留的，暂时没用放着就放着8
