### ISSUE TITLE
新功能：端侧过滤

### ISSUE THREAD

**Issue by Qiiamx** [yjl9903/resonance-market#51]
### Clear and concise description of the problem

我看到很多人在提导航和城市之类的
实际上我尝试了一下，更多时候仅仅是排序和导航是不足够的，以我为例，有以下情况
1、人在修城，不知道跑哪个货物（所谓城市快捷导航）
2、打开页面，按单票排序，发现**发动机**去**战备工厂**的单票利润最多（单票排序）
3、但是我买了G1发现仓库还空，又没有书，所以尝试在剩余的货物中，**按战备工厂单票利润倒序**（子排序）
4、于是矛盾出现了，选了城市排序就要自己找**第2步**，选了利润排序就要自己找**第3步**

### Suggested solution

对此提出这样的两个方案
1、新增一个模块，直接写个最优算法，让小伙伴自己输入 出发城市和目的城市（可选），前端算了给他，不显示其它城市

2、改造现在的页面
2.1 设置新增城市过滤，利润排序移动到表格列上（啊，没有看源码，写到这发现页面好像是服务端渲染来的，但是应该能移到前端的）
2.2 同时显示单位和单票利润（OR不嫌麻烦当然也可以按照排序选择显示）
2.3 浏览器缓存排序和筛选配置= =（说真的1和2感觉都没必要，缓存这个，其它的我个人是完全可以自适应的）

### Additional context

还要感谢一下product这个接口没有卡验证= =，用来写了个微信通知提醒我买沙金哈哈

**Comment by Ximu-Luya** [comment]
回复问题：
项目似乎刚开始时只是为了能够展示所有商品报价，并未考虑排序等功能，所以这部分代码写起来比较难搞，后续计划会单独出一个跑商规划计算功能模块。不过你提到的这个子排序，确实给了我新的功能思路，非常感谢！

回复解决方案：
1. 目前正在计划中，不过进度正处于“新建文件夹”，
2. 2.1这个改动有点大，目前这部分排序代码写得有点烂，估计后续要重构
3. 2.2目前按单票排序就是展示单票利润，按单位利润排序和城市城市顺序展示单位利润，同时展示，信息会太多了
4. 2.3缓存设置这个功能昨晚做了，但有bug临时下掉了，今晚修一修
