### ISSUE TITLE
代码格式化问题

### ISSUE THREAD

**Issue by Ximu-Luya** [yjl9903/resonance-market#56]
@yjl9903 话说你用的什么code format插件呀？看.vscode里是Prettier。你看我评论这里的这种span的标签，格式化得太逆天了。prettier的格式化，我个人认为很死板，目标是让代码更美观，但它的效果总是事与愿违。

详情请看（我还没弄明白怎么引用仓库中的代码）：https://github.com/yjl9903/resonance-market/commit/4f5c7fbfa39d39fd6628dd9de8db96f2d81f279d#r140109772

我之前特地手动改了好久，你这个commit又给全弄回来了（笑哭

这种情况对标签开闭的判断影响太大了（也不美观），另外还有其他属性换行问题，所以我一般从来都是自己手动format。另外，我是不用分号党，现在前端主流的论点是在Typescript中已经不再需要分号了。

所以你看是不是可以把这个commit给revert了，还有那个autofix.ci，因为一个分号阻断了部署工作流hhh

**Comment by yjl9903** [comment]
那看看怎么配一配 eslint 吧

加分号是我的习惯
