### ISSUE TITLE
[Proposal] 数据同步从轮询切换为 websocket 长连接

### ISSUE THREAD

**Issue by yjl9903** [yjl9903/resonance-market#61]
### Clear and concise description of the problem

半个多月已经 110m 次请求了，20 亿 ms cpu 时间，下个月账单可能要花几十刀。

![image](https://github.com/yjl9903/resonance-market/assets/30072175/57bdb079-1cb2-484b-b848-4e6b61961957)

提案切换成 ws 长连接，服务端主动推送数据：期望减少请求数，但是 cpu 时间可能会变多。

其它优化：
- [x] 配置 cdn：js,css,png,...
- [x] 限流：`/api/product`, `/api/log`, `/api/logs`, `/api/log/...`

**Comment by yjl9903** [comment]
![IMG_6366](https://github.com/yjl9903/resonance-market/assets/30072175/12f8baa5-9361-4eca-a251-5a2553a12a39)

**Comment by Ximu-Luya** [comment]
@yjl9903 好家伙这么夸张，所以ph这个动态是商会的？还是哪家的😂

**Comment by yjl9903** [comment]
盒🎁

**Comment by Ximu-Luya** [comment]
@yjl9903 我开服之前预下载的时候，iOS设备都没法安装，总是失败所以加了那个他们的客服-花姐，前几天发现他点赞了我的动态，我就知道他们知道我们在做的东西了，但没想到ph直接给发出来了

**Comment by Ximu-Luya** [comment]
我试了一下，谷歌搜索已经抓到咱们的网站了，但是百度似乎得去申请才行。我看下面评论很多人都不知道链接，然后百度也搜不到，不知道你有没有兴趣搞一下百度的搜索排名hhh。虽然我感觉咱们得先改名，我觉得“阿妮塔观测枢”这个名字还不错

**Comment by yjl9903** [comment]
@Ximu-Luya 讲个小故事：我的 https://garden.onekuma.cn 在二月份提交到百度的 seo 后台后的第二天，就开始受到了很大的异常流量攻击，直接导致我学了一下配 cf 上的防火墙和缓存规则。（只能说事实如此，异常流量有一部分是 aws 的 ai bot 爬的很猛

而且我操作了一下百度的那个 seo 控制台，没搞懂怎么用，上面那个提交了也没有任何效果

**Comment by yjl9903** [comment]
#63

**Comment by Ximu-Luya** [comment]
@yjl9903 好吧，这个记个todo吧。说实话我对这方面也不是很了解，前段时间工作上才搞了一下SEO优化，不过是找外包弄的方案，我当时也就是做了个移动端适配和TDK修改。异常攻击这事儿确实有点难搞

**Comment by Ximu-Luya** [comment]
@yjl9903 哦对了，如果你觉得运营成本难以承受的话，我可以帮忙承担一部分，看你

**Comment by yjl9903** [comment]
Implemented using server-send events in https://github.com/yjl9903/resonance-market/commit/32500943fc09716ae5afde122154f17a6c0a8826
