### ISSUE TITLE
请求增加阿妮塔发射中心的商品数据和其他城市的商品售卖价格。

### ISSUE THREAD

**Issue by chtlhap** [yjl9903/resonance-market#65]
### Clear and concise description of the problem

考虑阿妮塔发射中心已经上线，但雷索纳斯市场目前缺失阿妮塔发射中心的商品数据和其他篝火城商品在阿妮塔发射中心的售卖价格，不利于用户使用。

### Suggested solution

建议增加阿妮塔发射中心的商品数据和在其他篝火城商品在阿妮塔发射中心的售卖价格，接入已有的数据系统。

**Comment by yjl9903** [comment]
添加了阿妮塔发射中心相关的商品

@Ximu-Luya 从索思学会拉数据的脚本需要更新吗，我看好像暂时没数据

**Comment by yjl9903** [comment]
添加了
